theme = "tokyonight"

[editor]
mouse = true
line-number = "relative"
auto-info = true
auto-format = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"

[editor.lsp]
auto-signature-help = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
# character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels = 0

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = true
